name: Deploy Worker
on:
  push:
    branches:
      - dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: d1
          preCommands: |
            ls
            cp ./wrangler.toml.example wrangler.toml
            sed -i 's/database_id = ".*"/database_id = "${{ secrets.D1_DATABASE_ID }}"/' wrangler.toml